# Generated by Django 5.1 on 2025-04-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minder_name', models.CharField(max_length=100)),
                ('bus_colour_code', models.CharField(max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('date', models.DateField()),
                ('logistics_officer_number', models.CharField(max_length=20)),
                ('bus_route', models.TextField()),
                ('morning_trip', models.BooleanField(default=False)),
                ('afternoon_trip', models.BooleanField(default=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_signature', models.CharField(max_length=100)),
                ('number_of_children_picked', models.IntegerField()),
                ('children_returned', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
